import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Urbanist } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";
import { cn } from "@/lib/utils";
import CustomCursor from "@/components/custom-cursor";

const nexusbold = localFont({ src: "./fonts/Nexusbold.ttf", variable: '--font-nexus' });

const buildingstracks = localFont({src:"./fonts/Buildingsandundertherailwaytracksfree_ver.otf", variable: '--font-buildingstracks'})

const urbanist = Urbanist({ subsets: ['latin'], variable: '--font-mono' });

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable, nexusbold.variable, buildingstracks.variable, urbanist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <CustomCursor />
        {children}
        </body>
    </html>
  );
}
